language: python
python:
  - "2.7"
install:
  - "pip install coverage nose msgpack-python pyyaml python-coveralls"
script:
  - "coverage run --source=codemon setup.py test"
after_succes:
  - "coveralls"
